### ISSUE TITLE
the gpu vram stays same after certain generations

### ISSUE THREAD

**Issue by 14m35** [Auto1111SDK/Auto1111SDK#18]
OutOfMemoryError: CUDA out of memory. Tried to allocate 144.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 101.06 MiB is free. Process 20868 has 14.65 GiB memory in use. Of the allocated memory 14.32 GiB is allocated by PyTorch, and 191.06 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CON

it stays in 14gb doesnt go down after certain generations

**Comment by saketh12** [comment]
Will look into this, thanks for pointing this out.

**Comment by saketh12** [comment]
Can you please send me the code you were running for this? What models were you using? Were you using an XL checkpoint or a 1.5 checkpoint?

**Comment by saketh12** [comment]
Hey, I believe I just fixed this issue. At the end of each generation, simply adding the following snippet of code manages the vram fairly well:

```python
from modules import sd_samplers, images, shared, devices, processing, scripts
import gc; gc.collect()
devices.torch_gc()
```

So I've added to that end of each cell in the colab notebook. Btw, this was resolved by one of our users in our Discord. Feel free to join our discord for faster communication, as other members can also assist you!

I am closing this issue. If you still face bugs, reopen it or message it in the discord.
